# Generated by Django 3.1.1 on 2020-09-14 20:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20200914_1937'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='_id',
            new_name='pid',
        ),
    ]
