# Generated by Django 3.1.1 on 2020-09-16 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_sale_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='image',
        ),
    ]
